main = "index.js"
compatibility_date = "2022-05-25"

[env.dev]
name = "kanye-rest-dev"
workers_dev = true

[env.production]
name = "kanye-rest"
workers_dev = false
minify = true
route = "api.kanye.rest/*"